import { describe, expect, test, vi } from 'vitest';
import { Store } from '../../src/model/store';
import { snapshot, validateDocument, visibleIds } from '../../src/model/document';
import type { MindMapDocument, MindMapCommand } from '../../src/types';
import { referenceMap, node } from '../fixtures/maps';
const store = (extra = {}) => { let id=0; return new Store({document:referenceMap(),createNodeId:()=>`new-${id++}`,...extra}); };
const children = (s:Store,id:string) => s.model.nodes.get(id)!.children;
describe('validation and ownership',()=>{
  test.each([null,{}, {root:{}}, {root:node('')}, {root:{...node('r'),text:7}}, {root:{...node('r'),children:null}}, {root:{...node('r'),checked:null}}, {root:{...node('r'),collapsed:'yes'}}, {root:node('r','r',[node('x')])}])('rejects malformed documents (%j)',input=>expect(()=>validateDocument(input)).toThrow());
  test('rejects cycles, duplicate IDs, and shared objects',()=>{ const d=referenceMap();d.root.children[0]!.children.push(d.root);expect(()=>validateDocument(d)).toThrow();const e=referenceMap();e.root.children[0]!.id='root';expect(()=>validateDocument(e)).toThrow();const f=referenceMap();f.root.children.push(f.root.children[0]!);expect(()=>validateDocument(f)).toThrow(); });
  test('input and every snapshot are detached and schema-only',()=>{ const input=referenceMap();Object.assign(input.root,{extra:'discard'});const s=new Store({document:input});input.root.text='mutated';const snap=s.getDocument();snap.root.children.length=0;expect(s.getDocument().root.text).toBe('New Mindmap');expect(s.getDocument().root.children).toHaveLength(5);expect(s.getDocument().root).not.toHaveProperty('extra'); });
  test('handles a 12,000-level tree without recursion',()=>{ const document:MindMapDocument={root:{id:'r',text:'r',children:[{...node('0'),side:'left'}]}};let n=document.root.children[0]! as ReturnType<typeof node>;for(let i=1;i<12000;i++){const next=node(String(i));n.children.push(next);n=next;}const m=validateDocument(document);expect(m.nodes.size).toBe(12001);expect(validateDocument(snapshot(m)).nodes.size).toBe(12001);expect(visibleIds(m)).toHaveLength(12001); });
  test('invalid replacement preserves document, history, and selection',()=>{const s=store();s.execute({type:'setText',targetId:'one',text:'changed'});s.setSelection(['one']);const before=s.getDocument();expect(()=>s.setDocument({} as MindMapDocument)).toThrow();expect(s.getDocument()).toEqual(before);expect(s.selection.ids).toEqual(['one']);expect(s.history.canUndo).toBe(true);s.setDocument(referenceMap());expect(s.history.canUndo).toBe(false);expect(s.selection.ids).toEqual(['root']);});
});
describe('atomic structure and IDs',()=>{
  test.each([()=>'',()=>'root',()=>{throw new Error('host');},()=>42])('bad ID callback rejects without side effects',createNodeId=>{const s=store({createNodeId});const before=s.getDocument();s.execute({type:'collapse',targetId:'one'});const collapsed=s.getDocument();s.setSelection(['one']);expect(()=>s.execute({type:'insertChild'})).toThrow();expect(s.getDocument()).toEqual(collapsed);expect(s.selection.ids).toEqual(['one']);s.execute({type:'undo'});expect(s.getDocument()).toEqual(before);});
  test('canExecute never invokes host callbacks',()=>{const callback=vi.fn(()=> 'id');const s=store({createNodeId:callback});expect(s.canExecute({type:'insertChild'})).toBe(true);expect(callback).not.toHaveBeenCalled();});
  test('root insertion follows side-specific document slots',()=>{const s=store();s.execute({type:'insertChild',targetId:'root'});expect(children(s,'root')).toEqual(['child1','child2','one','two','three','new-0']);s.execute({type:'insertBefore',targetId:'root'});expect(children(s,'root')[2]).toBe('new-1');s.execute({type:'insertParent',targetId:'root'});expect(children(s,'root')[2]).toBe('new-2');expect(s.model.nodes.get('new-2')!.side).toBe('left');});
  test('empty-side insertion appends; wrapping transfers side and has no checkbox',()=>{const s=store();s.execute({type:'addCheckbox',ids:['one']});s.execute({type:'insertParent',targetId:'one'});expect(s.model.nodes.get('new-0')).toMatchObject({side:'right',children:['one']});expect(s.model.nodes.get('new-0')!.checked).toBeUndefined();expect(s.model.nodes.get('one')!.side).toBeUndefined();s.execute({type:'undo'});expect(s.model.nodes.get('one')!.side).toBe('right');const r=new Store({document:{root:{id:'r',text:'r',children:[]}},createNodeId:()=> 'x'});r.execute({type:'insertParent'});expect(r.model.nodes.get('x')!.side).toBe('left');});
  test('new child/sibling inherits checkbox presence, starts unchecked, and expands parent',()=>{const s=store();s.execute({type:'addCheckbox',ids:['one']});s.execute({type:'toggleChecked',ids:['one']});s.execute({type:'collapse',targetId:'one'});s.execute({type:'insertChild',targetId:'one',text:'final'});expect(s.model.nodes.get('new-0')).toMatchObject({text:'final',checked:false});expect(s.model.nodes.get('one')!.collapsed).toBe(false);s.execute({type:'undo'});expect(s.model.nodes.get('one')!.collapsed).toBe(true);expect(s.model.nodes.has('new-0')).toBe(false);s.execute({type:'insertBefore',targetId:'one'});expect(s.model.nodes.get('new-1')!.checked).toBe(false);});
  test('normalizes ancestor selections, protects root, and allows deleting all branches',()=>{const s=store();s.setSelection(['one','a'],'a');s.execute({type:'delete'});expect(s.model.nodes.has('one')).toBe(false);expect(s.model.nodes.has('a')).toBe(false);expect(s.selection.ids).toEqual(['root']);s.execute({type:'undo'});expect(s.selection.ids).toEqual(['one','a']);expect(s.execute({type:'delete',ids:['root','one']})).toBe(false);expect(s.execute({type:'move',ids:['root'],destination:{targetId:'one',position:'child'}})).toBe(false);s.execute({type:'delete',ids:[...children(s,'root')]});expect(s.model.nodes.size).toBe(1);});
  test('unknown target in a group rejects entire command',()=>{const s=store();const before=s.getDocument();expect(()=>s.execute({type:'delete',ids:['one','missing']})).toThrow();expect(s.getDocument()).toEqual(before);expect(s.history.canUndo).toBe(false);});
  test('move validates cycles, adopts sides, preserves IDs and detects effective no-op',()=>{const s=store();const before=s.getDocument();expect(()=>s.execute({type:'move',ids:['one'],destination:{targetId:'a',position:'child'}})).toThrow();expect(s.getDocument()).toEqual(before);expect(s.execute({type:'move',ids:['a','b'],destination:{targetId:'c',position:'before'}})).toBe(false);expect(s.history.canUndo).toBe(false);s.execute({type:'move',ids:['a','b'],destination:{targetId:'child1',position:'after'}});expect(children(s,'root')).toEqual(['child1','a','b','child2','one','two','three']);expect(s.model.nodes.get('a')!.side).toBe('left');s.execute({type:'undo'});expect(s.getDocument()).toEqual(before);s.execute({type:'redo'});expect(s.model.nodes.get('a')!.side).toBe('left');});
  test('multi-parent moves normalize ancestry and use supplied visual order',()=>{const s=store();s.visualOrder=['two','one','a'];s.execute({type:'move',ids:['a','one','two'],destination:{targetId:'child2',position:'child'}});expect(children(s,'child2').slice(-2)).toEqual(['two','one']);expect(s.model.nodes.get('one')!.side).toBeUndefined();});
  test('drop into collapsed parent keeps it collapsed and selects visible target',()=>{const s=store();s.execute({type:'move',ids:['a'],destination:{targetId:'collapsed',position:'child'}});expect(s.model.nodes.get('collapsed')!.collapsed).toBe(true);expect(s.selection.ids).toEqual(['collapsed']);});
});
describe('history, checkbox, collapse, and read-only',()=>{
  test('mixed checkbox state checks all, independently of descendants',()=>{const s=store();s.execute({type:'addCheckbox',ids:['one','a']});s.execute({type:'toggleChecked',ids:['one']});s.execute({type:'toggleChecked',ids:['one','a','b']});expect(s.model.nodes.get('one')!.checked).toBe(true);expect(s.model.nodes.get('a')!.checked).toBe(true);expect(s.model.nodes.get('b')!.checked).toBeUndefined();expect(s.lastGeometry).toBe(false);s.execute({type:'toggleChecked',ids:['one','a']});expect(s.model.nodes.get('a')!.checked).toBe(false);s.execute({type:'undo'});expect(s.model.nodes.get('a')!.checked).toBe(true);s.execute({type:'addCheckbox',ids:['one','b']});expect(s.model.nodes.get('one')!.checked).toBe(true);expect(s.model.nodes.get('b')!.checked).toBe(false);s.execute({type:'removeCheckbox',ids:['one']});expect(s.model.nodes.get('one')!.checked).toBeUndefined();expect(s.lastGeometry).toBe(true);});
  test('collapse cleans hidden selection and undo restores it',()=>{const s=store();s.setSelection(['a','b'],'b');s.execute({type:'collapse',targetId:'one'});expect(s.selection.ids).toEqual(['one']);expect(visibleIds(s.model)).not.toContain('a');s.execute({type:'undo'});expect(s.selection).toEqual({ids:['a','b'],activeId:'b'});expect(s.execute({type:'toggleCollapse',targetId:'a'})).toBe(false);});
  test('no-ops preserve redo; mutations clear it; bounded history and selection are separate',()=>{const s=store({historyLimit:2});s.execute({type:'setText',targetId:'one',text:'1'});s.execute({type:'setText',targetId:'one',text:'2'});s.execute({type:'setText',targetId:'one',text:'3'});s.execute({type:'undo'});s.setSelection(['two']);expect(s.execute({type:'setText',targetId:'one',text:'2'})).toBe(false);expect(s.history.canRedo).toBe(true);s.execute({type:'undo'});expect(s.execute({type:'undo'})).toBe(false);expect(s.model.nodes.get('one')!.text).toBe('1');s.execute({type:'addCheckbox',ids:['one']});expect(s.history.canRedo).toBe(false);});
  test.each(['insertChild','insertBefore','insertAfter','insertParent','setText','delete','toggleChecked','addCheckbox','removeCheckbox','toggleCollapse','collapse','expand','move','undo','redo'])('read-only rejects %s centrally',type=>{const s=store({readonly:true});const cmd={type,targetId:'one',ids:['one'],text:'x',destination:{targetId:'two',position:'child'}} as MindMapCommand;const before=s.getDocument();expect(s.canExecute(cmd)).toBe(false);expect(()=>s.execute(cmd)).toThrow(/read-only/);expect(s.getDocument()).toEqual(before);s.setSelection(['two']);s.setDocument(referenceMap());});
});
